pulp/pulp_puppet

- pulp_puppet_plugins/test/unit/test_forge_api.py
https://bugzilla.redhat.com/show_bug.cgi?id=1184187
**The Problem**
Line 21 causes a cascading import which executes db.connection.initialize(). That method will initialize the database based on server.conf. Mongoengine then replaces the 'default' database used going forward with the server.conf production database. Tests drop database collections which causes the symptom of BZ 1184187.
**The Solution**
By calling initialize(name='pulp_unittest') after the import it will switch the DB back to the unittest. I could not see any side effects from having api initialize the DB to the production database and immediately after initialize it back to the test database immediately after.
**This is a quick fix**
This change does not come with unittests because a more comprehensive fix is being …
> 1184187 - Causes all tests to use pulp_unittest

- pulp_puppet_plugins/pulp_puppet/plugins/distributors/publish.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/copier.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_copier.py
Platform had some silly imports in pulp.plugins that were only there so
that plugins don't import pulp.server. These imports were angering
flake8 (for good reason). This commit fixes pulp_puppet's imports so
they import from the real place that the code lived.
> Respond to PEP-8 changes in platform.

- docs/tech-reference/plugin_conf.rst
- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
When this distributor gets removed from a repository, such as when the repository
gets deleted, all modules in its install path will be deleted.
closes #732
https://pulp.plan.io/issues/732
> The install-distributor now cleans up (deletes) modules on removal from a repo

- docs/tech-reference/plugin_conf.rst
- docs/user-guide/release-notes/2.7.x.rst
- docs/user-guide/release-notes/index.rst
This goes with #170 , but is in a separate PR because a major user wants to cherry-pick the code changes in that PR onto pulp 2.6.0. It was easier to put the release notes in a separate PR, so the original can apply cleanly to 2.6.0.
> Adding release notes for 2.7.0

- pulp_puppet_plugins/pulp_puppet/plugins/importers/metadata.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_metadata.py
The implementation was using a depth-first-search which did not
traverse in the same order on all platforms. Some Puppet modules
contain other modules as dependencies, and the DFS implementation
could incorrectly find the wrong one. This uses a very dumb
approach which looks for metadata.json in the top level folder
of the the tar.gz uploaded Puppet module. This is based on the
Puppet packaging guidelines [0].
[0]:  https://docs.puppetlabs.com/puppet/latest/reference/modules_fundamentals.html#module-fundamentals
https://pulp.plan.io/issues/890
closes #890
> Updates metadata.json search to look in first top-level folder

- docs/tech-reference/type.rst
- docs/user-guide/installation.rst
- docs/user-guide/introduction.rst
- docs/user-guide/quick-start.rst
- docs/user-guide/release-notes/2.7.x.rst
- docs/user-guide/troubleshooting.rst
- pulp_puppet_extensions_admin/pulp_puppet/extensions/admin/repo/upload.py
- pulp_puppet_extensions_admin/test/unit/test_extension_upload.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/metadata.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_metadata.py
This patch ensures that pulp-admin submits an empty string when making a request
to upload a puppet module. The unit key is generated on the server based on the
content of metadata.json found in the top level directory of a puppet module.
closes #920
> Removed generation of unit key based on file name of puppet module

- docs/tech-reference/plugin_conf.rst
- docs/user-guide/release-notes/2.7.x.rst
- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
https://pulp.plan.io/issues/732
This is an slight modification of the original implementation's behavior.
> Repo delete now causes install distributor to delete the environment's directory

- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- test_requirements.txt
closes #86
https://pulp.plan.io/issues/86
Unit metadata dictionary needed to be updated and not replaced.
> As a user, I can add mutable custom metadata to a unit.

- pulp_puppet_tools/test/unit/test_puppet_module_builder.py
- run-tests.py
This also includes a fix for a test in that module that was failing.
closes #1276
> Unit tests in pulp_puppet_tools are now run by run-tests.py

- docs/tech-reference/plugin_conf.rst
- docs/user-guide/release-notes/2.8.x.rst
- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
Also resurrected a bunch of unit tests for the install distributor that had
been removed during the mongoengine conversion.
fixes #1289
https://pulp.plan.io/issues/1289
> Install distributor now normalizes uid, gid, and filesystem permissions.

- pulp_puppet_tools/pulp_puppet/tools/puppet_module_builder.py
- pulp_puppet_tools/test/unit/test_puppet_module_builder.py
pulp-puppet-module-builder fails to parse non-english git output:
> echo $LANG
de_DE.UTF-8
> pulp-puppet-module-builder -u git+ssh://…
cd /root
git clone --recursive git+ssh://…
Password: 
cd idms-puppet
git status
git remote show -n origin
Traceback (most recent call last):
File "/usr/bin/pulp-puppet-module-builder", line 9, in <module>
load_entry_point('pulp-puppet-tools==2.6.0', 'console_scripts', 'pulp-puppet-module-builder')()
File "/usr/lib/python2.7/site-packages/pulp_puppet/tools/puppet_module_builder.py", line 340, in main
git_checkout(options)
File "/usr/lib/python2.7/site-packages/pulp_puppet/tools/puppet_module_builder.py", line 204, in     git_checkout
if not options.origin:
AttributeError: Values instance has no attribute 'origin'
>
> Fixes broken parsing of git output for LANG=de_DE.UTF-8 (and others).

- pulp_puppet_plugins/pulp_puppet/plugins/db/models.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py
The platform recently removed `set_content` and replaced it with
`import_content`. The `import_content` method requires the unit to be
saved prior to calling it, as the unit needs a uuid before its storage
path can be calculated. This commit fixes pulp_puppet to work with
`import_content`.
> Fix the usage of import_content in pulp_puppet.

- pulp-puppet.spec
The package name has changed to match Fedora's package name: https://github.com/pulp/pulp/commit/c73d1dee8725064485e27797886cbd9936dd415c
> Update python-semantic-version to python-semantic_version in spec.

- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py
Updating repository units from platform, due to them
not being reliably updated by plugins. The code to do
this lives in platform, so we should be able to utilize it
from there
https://pulp.plan.io/issues/1467
re #1467
> Update repository units from platform

- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_upload.py
Call save_and_import_content().
re #[1457](https://pulp.plan.io/issues/1457)
https://pulp.plan.io/issues/1457
> Ensure file objects are cleaned up on error

- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
During conversion to mongoengine the check for already existing units
broke. This fixes that problem.
https://pulp.plan.io/issues/1440
closes #1440
> Adds use of GetLocalUnitsStep to track which units already exist in Pulp

- pulp_puppet_plugins/pulp_puppet/plugins/db/models.py
This uniqueness contstraint is now enforced by the platform for all content units.
https://pulp.plan.io/issues/1477
re: 1477
> Removes uniqueness constraint on unit key

- pulp_puppet_tools/pulp_puppet/tools/puppet_module_builder.py
- pulp_puppet_tools/test/unit/test_puppet_module_builder.py
https://pulp.plan.io/issues/1309
Fix git URLs with trailing /.
Fix --clean to use git checkout directory derived from the URL.
> Fix --clean option.

- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
https://pulp.plan.io/issues/1607
closes #1607
> Stop re-raising exceptions during the removal of install_path

- pulp-puppet.spec
https://pulp.plan.io/issues/538
closes #538
Originally fixed here:
https://github.com/pulp/pulp_puppet/pull/151/
The fix was accidentally removed in a merge conflict.
> require python-pulp-puppet-common

- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
- pulp_puppet_plugins/test/unit/plugins/importer/downloaders/test_local.py
- pulp_puppet_plugins/test/unit/plugins/importer/downloaders/test_web.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_forge.py
This also fixes some test failures that were already present
related to working directories being created outside of a celery
task.
Pulp smash also passed before and after this commit locally.
closes #1780
https://pulp.plan.io/issues/1780
> Puppet modules saved from PULP_MANIFEST use correct paths

- docs/conf.py
- docs/user-guide/recipes.rst
- docs/user-guide/release-notes/2.8.x.rst
`make html` now builds cleanly without any errors or warnings.
https://pulp.plan.io/issues/950
re #950
> Fixes docs build errors and warnings

- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
This commit fixes a problem where the Forge importer would skip
importing units into a repository if the unit already existed in Pulp.
This patch does not address the problem that the importer will download
a module even if it already exists within Pulp; that issue is being
tracked in https://pulp.plan.io/issues/1943
fixes #1937
> Forge importer now queries the repo units instead of all units

- docs/Makefile
- docs/conf.py
- docs/user-guide/configuration.rst
- docs/user-guide/installation.rst
- docs/user-guide/release-notes/2.1.x.rst
- docs/user-guide/release-notes/2.2.x.rst
Intersphinx was preventing the strict mode from being enabled
due to docs being built in a network isolated mock environment.
Intersphinx was also going to break because it is tied
to URLs from ReadTheDocs. Now intersphinx is removed, and
usage of it was dropped from the content. Strict Sphinx
mode is now enabled.
Links are also updated to point to docs.pulpproject.org
https://pulp.plan.io/issues/2034
re #2034
> Remove intersphinx and enable Strict mode

- pulp_puppet_plugins/pulp_puppet/plugins/migrations/0004_standard_storage_path.py
Migration 4 can take a long time. This outputs a banner to
the logs and the foreground of pulp-manage-db warning the user
that it could take a long time.
https://pulp.plan.io/issues/2060
re #2060
> Adds banner warning about migration runtime

- pulp_puppet_tools/pulp_puppet/tools/puppet_module_builder.py
- pulp_puppet_tools/test/unit/test_puppet_module_builder.py
By default, no longer overwrite modules in the output dir. Also, added a force
flag which can override this behavior.
fixes #1853
https://pulp.plan.io/issues/1853
> Don't ovewrite modules unless force flag is true

- docs/tech-reference/plugin_conf.rst
- docs/user-guide/release-notes/2.13.x.rst
- flake8.cfg
- pulp_puppet_common/pulp_puppet/common/constants.py
- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
Puppet master modules should be allowed to be installed in a MYENV/modules directory where deleting the puppet repo should remove the MYENV directory. This allows the user
to specify a subdir in which modules could be installed.
closes #2108
https://pulp.plan.io/issues/2108
> Add subdir option to puppet install distributor

- docs/conf.py
- docs/user-guide/release-notes/2.6.x.rst
- docs/user-guide/release-notes/2.7.x.rst
- docs/user-guide/release-notes/2.8.x.rst
re #2585
https://pulp.plan.io/issues/2585
> Modify directive name to generate docs correctly using platfrom config

- pulp_puppet_extensions_admin/pulp_puppet/extensions/admin/repo/cudl.py
- pulp_puppet_extensions_admin/test/unit/extensions/admin/repo/test_cudl.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_forge.py
Fix remove_missing option for the forge and directory importers.
Do not re-download units if they are in DB and on a disk for the forge importer.
closes #2606
https://pulp.plan.io/issues/2606
> Fix remove_missing option and unnecessary downloads for forge importer

- pulp-puppet.spec
Add provides for python2-* packages.  Fedora downstream packages are
named python2-* and provide python-*.  Upstream needs to mirror this for
dependency resolution to work properly
re #2687
> Add provides for python2-* packages

- docs/user-guide/troubleshooting.rst
- pulp_puppet_plugins/pulp_puppet/plugins/db/models.py
- pulp_puppet_plugins/pulp_puppet/plugins/error_codes.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/importer.py
- pulp_puppet_plugins/pulp_puppet/plugins/importers/metadata.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_importer.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_metadata.py
- pulp_puppet_plugins/test/unit/plugins/importer/test_upload.py
closes #2512
https://pulp.plan.io/issues/2512
> Allow puppet upload errors to propagate

- pulp_puppet_plugins/pulp_puppet/plugins/importers/metadata.py
Pulp was unable to find metadata in certain modules that had MacOS
content because it was simply selecting the first file OR dir. Changing
this to filter the list of entries to only dirs.
fixes #1846
https://pulp.plan.io/issues/1846
Note: I couldn't reproduce this in my pulp dev environment. I had to use a Satellite 6.2 box for whatever reason. I'm guessing maybe the ordering of the files is nondeterministic as sometimes the directory gets listed first:
```
(Pdb) os.listdir(extraction_dir)
['marcel-passenger-0.5.0', '._marcel-passenger-0.5.0']
```
> Fixing bug where modules had extraneous files

- pulp-puppet.spec
The Source0 currently does not lead to the correct source file.
This updates the spec file and renames the source to what would be
the expected source name.
ref #2784
https://pulp.plan.io/issues/2784
> Update spec files Source0

- AUTHORS
- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
Added validation to check if distributor_config is specified while associating distributor to repository.
[Issue 1237](https://pulp.plan.io/issues/1237)
> 1237 - distributor config

- AUTHORS
- pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py
- pulp_puppet_plugins/test/unit/test_install_distributor.py
Config validation was returning True instead of False when a distributor_config
was not specified while associating a distributor to a repository.
closes #1237
https://pulp.plan.io/issues/1237
> Update Puppet module install_distributor

- docs/tech-reference/plugin_conf.rst
F27+ changed the behavior of semanage to set a selinux boolean by
default, but not change its current state. Update docs to advise users
of this to avoid confusion when rsync distributors fail to run with
selinux in F27.
re #3347
https://pulp.plan.io/issues/3347
> Advise users on using setsebool to set pulp_manage_rsync selinux boolean
