pulp/pulp_puppet

pulp_puppet_extensions_admin/pulp_puppet/extensions/admin/consumer/content.py
This must be merged before https://github.com/pulp/pulp/pull/1703.
=> Fix some import errors due to PEP-8 fixes in platform.

docs/conf.py, docs/user-guide/release-notes/2.3.x.rst, docs/user-guide/release-notes/2.4.x.rst, docs/user-guide/release-notes/2.5.x.rst, docs/user-guide/release-notes/2.6.x.rst
=> Updates exlinks and usages for the move to redmine.

pulp_puppet_extensions_admin/test/unit/test_extension_modules.py, pulp_puppet_plugins/test/unit/test_install_distributor.py, pulp_puppet_plugins/test/unit/test_profiler_whole_repo.py
https://pulp.plan.io/issues/849
depends on https://github.com/pulp/pulp/pull/1783
=> Remove the owner_type and owner_id fields from the repo_content_unit

docs/user-guide/configuration.rst
=> Fixed link to importers config

pulp_puppet_extensions_admin/pulp_puppet/extensions/admin/repo/remove.py
Changes done in pulp, pulp_rpm, pulp_puppet.
=> Issue 662: Minor Fix in documentation

pulp_puppet_plugins/pulp_puppet/plugins/migrations/0001_puppet_module_unit_checksum.py
https://pulp.plan.io/issues/1065
https://github.com/pulp/pulp/pull/2044
re #1065
=> rm safe=true

pulp_puppet_plugins/pulp_puppet/plugins/db/models.py, pulp_puppet_plugins/pulp_puppet/plugins/distributors/filedistributor.py, pulp_puppet_plugins/pulp_puppet/plugins/distributors/installdistributor.py, pulp_puppet_plugins/pulp_puppet/plugins/distributors/publish.py, pulp_puppet_plugins/test/unit/plugins/distributors/test_filedistributor.py, pulp_puppet_plugins/test/unit/test_install_distributor.py
* renames source_location to _source_location
* renames unit_type_id to _content_type_id
* Updates tests so they pass too
=> Updates plugin to match platform changes on ContentUnit

pulp_puppet_plugins/pulp_puppet/forge/releases.py, pulp_puppet_plugins/test/unit/forge/test_releases.py
It was really hard to update the code because my linter was freaking out, so I also PEP8'ed it.
=> update for core conversion of distributors collection to mongoengine

pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py, pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py, pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py
https://pulp.plan.io/issues/1425
Looks like this area of code is not covered by unit tests.  Will try to add if I have time.
=> ref #1425 - compatibility changes with lazy platform.

pulp_puppet_plugins/pulp_puppet/forge/urls.py, pulp_puppet_plugins/pulp_puppet/forge/wsgi.py, pulp_puppet_plugins/usr/share/pulp/wsgi/puppet_forge.wsgi
https://pulp.plan.io/issues/1599
closes #1599
=> Fixes Puppet Forge wsgi application entry point

pulp_puppet_plugins/test/unit/__init__.py
https://pulp.plan.io/issues/413
re #413
=> Block attempts to load server.conf when running tests

pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py, pulp_puppet_plugins/pulp_puppet/plugins/importers/forge.py, pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py
=> Adds check for duplicate unit key

pulp_puppet_tools/pulp_puppet/tools/puppet_module_builder.py, pulp_puppet_tools/test/unit/test_puppet_module_builder.py
=> Revert "Fix --clean option."

pulp_puppet_plugins/pulp_puppet/plugins/migrations/0004_standard_storage_path.py, pulp_puppet_plugins/test/unit/plugins/migrations/test_0004_standard_storage_path.py
=> standard storage path migration.

docs/user-guide/release-notes/2.8.x.rst, pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py, pulp_puppet_plugins/pulp_puppet/plugins/migrations/0005_puppet_module_name_change.py, pulp_puppet_plugins/test/unit/plugins/migrations/test_0005_puppet_module_name_change.py
closes #1879
https://pulp.plan.io/issues/1879
=> Incorrect name when syncing puppet module from the filesystem.

pulp_puppet_plugins/pulp_puppet/plugins/importers/upload.py, pulp_puppet_plugins/test/unit/plugins/importer/test_upload.py
closes #1950
https://pulp.plan.io/issues/1950
=> Fix module upload failure when module's name is in format author/name.

pulp-dev.py, run-tests.py
closes #2296
https://pulp.plan.io/issues/2296
=> Pulp3: Rewrite shebangs to python3

pulp_puppet_plugins/pulp_puppet/plugins/importers/directory.py
closes #1981
https://pulp.plan.io/issues/1981
=> 1981 - Unnecessary pulp error on puppet repo sync.

docs/user-guide/release-notes/2.10.x.rst, docs/user-guide/release-notes/2.11.x.rst, docs/user-guide/release-notes/2.12.x.rst, docs/user-guide/release-notes/2.8.x.rst, docs/user-guide/release-notes/2.9.x.rst, docs/user-guide/release-notes/index.rst
closes #2581
https://pulp.plan.io/issues/2581
=> Add release notes for all pulp puppet release

pulp-puppet.spec
re #2679
https://pulp.plan.io/issues/2679
=> Don't build unsupported packages in el6 by default

pulp_puppet_plugins/pulp_puppet/forge/urls.py
fixes #2750
https://pulp.plan.io/issues/2750
=> Supporting django 1.6-1.11

pulp-puppet.spec
Add obsoletes to spec file
refs #[2639](https://pulp.plan.io/issues/2639)
=> Add obsoletes to spec file

pulp_puppet_common/setup.py, pulp_puppet_extensions_admin/setup.py, pulp_puppet_plugins/setup.py
ref #2444
https://pulp.plan.io/issues/2444
=> Update setup.py for pulp3 PyPI packaging

docs/user-guide/release-notes/2.15.x.rst, docs/user-guide/release-notes/index.rst
Pulling forward 2.15.0 release notes changes
=> 2.15 release notes

pulp_puppet_plugins/pulp_puppet/plugins/distributors/publish.py
closes #3753
https://pulp.plan.io/issues/3753
=> Use pulp-provided md5 util for fips compatibility
